# Generated by Django 4.1.1 on 2022-11-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_coursedetail_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.CharField(blank=True, max_length=221, null=True),
        ),
    ]
