# Generated by Django 4.1.1 on 2022-11-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_course_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.CharField(blank=True, max_length=221, null=True),
        ),
    ]
