# Generated by Django 4.1.1 on 2022-11-03 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lessons',
        ),
    ]
